build: debian: support bullseye
The new stable version has:

- security repo has a different release dir
- fakeroot is not longer part of the 'build-dep linux'
- modinfo needs to be explicitly removed
- the version needs a dash to avoid this error:

  error: non-native package version does not contain a revision

Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>